name: Lint

on:
  push:
    # Run on all branches
    branches:
      # include
      - '**'

    # Run on changes in the etc folder
    # Run on any file change
    paths:
      - '**/*.py'
  pull_request:
    # Run on all branches
    branches:
      - '**'
    # Run on any file change
    paths:
      - etc/**
      - '**/*.py'

paths:
  - etc/**
  - '**/*.py'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
